export const siteData = {
  name: 'Justin Hou',
  tagline: 'CS @ Columbia · I.I. Rabi Scholar',
  email: 'justin.hou@columbia.edu',
  photo: '/assets/justin.png',
  about: [
    "I study computer science at Columbia and spend most of my week between building projects in memory and continual learning, supporting builders in CORE, and meeting cool people building cool things. Right now I'm building Adela and Trace, researching RLMs with Richard Zemel, and running CORE — Columbia's biggest entrepreneurship community. This summer I'm joining Altara as an FDE.",
    'Outside of that I produce music, play electric guitar in a band, and once got talked into walking a runway. I also play a little chess and a respectable amount of water polo.',
  ],
  currently: [
    { label: 'Incoming', detail: 'FDE @ Altara' },
    { label: 'Building', detail: 'Adela' },
    { label: 'President', detail: "Columbia's Organization of Rising Entrepreneurs (CORE)" },
    { label: 'Scout', detail: 'Soma Capital' },
    { label: 'Venture Fellow', detail: 'Xfund' },
  ],
  previously: [
    { year: '2026', text: 'Researcher, Creative Machines Lab' },
    { year: '2025', text: 'Director, Almaworks Accelerator' },
    { year: '2024', text: 'Researcher, Computational Morphogenomics Lab' },
    { year: '2024', text: 'Investment analyst, TSV Capital (early-stage AI)' },
    { year: '2022', text: 'ML intern, Lockheed Martin Solar & Astrophysics Lab' },
    { year: '2020', text: 'Founded Lucidity — classroom focus tool, piloted in 50+ classes' },
  ],
  projects: [
    { name: 'Vibe Check', year: '2026', blurb: 'Browser agents for site reliability diagnosis agent.', href: 'https://github.com/TobyKThurston/ParallelAgents' },
    { name: 'Trace', year: '2026', blurb: 'Press a hotkey to record a workflow, watch as Hermes Agent learns, automates ane executes it.', href: 'https://github.com/boovines/trace' },
    { name: 'MARLM', year: '2025', blurb: 'Memory-Augmented Recursive Language Model', href: 'https://github.com/boovines/MARLM' },
    { name: 'Adela', year: '2026', blurb: 'Structured SOPs from engineering knowledge.', href: 'https://github.com/boovines/forward' },
    { name: 'Vision-Prompt Glasses', year: '2025', blurb: 'Smart glasses that summon micro-agents with a gesture.', href: 'https://github.com/boovines/FPCV-Final-Project' },
    { name: 'Granted', year: '2025', blurb: 'Grant-writing copilot for non-profits and research labs.', href: 'https://github.com/boovines/Granted' },
    { name: 'Morning Joe', year: '2025', blurb: 'Personal news radar — what your friends are reading.', href: 'https://github.com/boovines/morningjoe' },
    { name: 'Solar Eruptivity RNN', year: '2023', blurb: 'Recurrent net for predicting solar active-region eruptions.', href: 'https://github.com/boovines/LMSALDataSetupTask' },
    { name: 'Patches (OSS)', year: '2024', blurb: 'Retriever pipeline contribution to the Patches generative-SLM library.', href: 'https://github.com/Computational-Morphogenomics-Group/Ladder' },
    { name: 'Debris Disks', year: '2021', blurb: 'Discovery of debris disks in habitable Kepler planet candidates. AAS 239.', href: 'https://aas.org/meetings/aas239/2nd-media-advisory#thur_1' },
  ],
  also: [
    { tag: 'music', text: 'I produce, mostly at night. Used to play electric guitar in a band.' },
    { tag: 'runway', text: 'Walked a runway once. Was told to look bored. Nailed it.' },
    { tag: 'chess', text: 'Daily puzzles, currently stuck around 1700.' },
    { tag: 'water polo', text: 'Eggbeater kick is underrated cardio.' },
    { tag: 'golf', text: 'Slowly getting better at not getting worse.' },
  ],
  links: [
    { label: 'GitHub', href: 'https://github.com/boovines' },
    { label: 'LinkedIn', href: 'https://linkedin.com/in/justinhou2005' },
    { label: 'X', href: 'https://twitter.com/justinhou25' },
    { label: 'Email', href: 'mailto:justin.hou@columbia.edu' },
  ],
}
